use_frameworks!

platform :ios, '10.0'

target 'WebRTCAudioProcessing_Example' do
  pod 'WebRTCAudioProcessing', :path => '../WebRTCAudioProcessing'

  target 'WebRTCAudioProcessing_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
