use_frameworks!

platform :ios, '12.0'

target 'WebRTCAudioProcessing_Example' do
  pod 'WebRTCAudioProcessing', :path => '../'
	
  #pod 'WebRTCAudioProcessing'
	
  #pod 'WebRTCAudioProcessing', '1.0.5.1'

  target 'WebRTCAudioProcessing_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
